### ISSUE TITLE
uninitialized constant Grape::Formatter::Base (NameError)

### ISSUE THREAD

**Issue by scalp42** [rosylilly/grape-msgpack#3]
grape `0.15.0` is breaking `grape-msgpack`, culprit seems to be https://github.com/ruby-grape/grape/commit/93e699829f7b4a2fe152370eccdf9b2712f4329f

Any chance you could take a look @rosylilly ?

Thanks in advance :smile:

**Comment by rosylilly** [comment]
I'm fixing it on #4 . Please wait a little longer until it merge.

**Comment by scalp42** [comment]
Thanks a lot @rosylilly :100:

**Comment by rosylilly** [comment]
v0.2.0 released.
